apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  namespace: sonarqube
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: sonarqube
    app.kubernetes.io/component: sonarqube
    app.kubernetes.io/instance: sonarqube
  name: sonarqube
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: sonarqube
    from:
      kind: DockerImage
      name: sonarqube
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source