apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: argo4u-dev-eventlistener
  namespace: argo4u-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: argo4u-dev-trigger