apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bankaccount-dev-eventlistener
  namespace: bankaccount-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: bankaccount-dev-trigger