apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: capacity-tool
  name: el-capacity-tool-dev-route
  namespace: capacity-tool-dev
spec:
  host: el-capacity-tool-dev.apps.ocp-lab.its4u.eu
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-capacity-tool-dev-eventlistener
    weight: 100
  wildcardPolicy: None