apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dms-dev-eventlistener
  namespace: dms-dev
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: dms-dev-trigger