apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: erp-api-dev-trigger
  namespace: erp-api-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: erp-api-dev-triggerbinding
  template:
    ref: erp-api-dev-triggertemplate