apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: alexandre-dev-trigger
  namespace: alexandre-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: alexandre-dev-triggerbinding
  template:
    ref: alexandre-dev-triggertemplate