apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: lns-dev-trigger
  namespace: lns-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: lns-dev-triggerbinding
  template:
    ref: lns-dev-triggertemplate