apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: bankaccount-dev-trigger
  namespace: bankaccount-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: bankaccount-dev-triggerbinding
  template:
    ref: bankaccount-dev-triggertemplate