apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: christopher-dev-trigger
  namespace: christopher-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: christopher-dev-triggerbinding
  template:
    ref: christopher-dev-triggertemplate