apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: ctie-dev-trigger
  namespace: ctie-dev
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: ctie-dev-triggerbinding
  template:
    ref: ctie-dev-triggertemplate