apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  namespace: nexus3
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: nexus3
    app.kubernetes.io/component: nexus3
    app.kubernetes.io/instance: nexus3
  name: nexus3
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: sonatype/nexus3
    from:
      kind: DockerImage
      name: sonatype/nexus3
    generation: 2
    importPolicy: {}
    name: latest
    referencePolicy:
      type: Source
